### ISSUE TITLE
SPI PINS

### ISSUE THREAD

**Issue by 5vi5t** [awawa-dev/HyperSerialEsp8266#2]
what pins to use for spi?
data pin and clock pin?
in neopixelbus the software spi method is selected, not the hardware method. Why?) D5 and D7 is simple

**Comment by awawa-dev** [comment]
Hi
In HyperSerialEsp8266 conventional NeoPixelBus' constructor  is used (with only led number is passed as an argument) so hardware SPI method should be selected.

**Comment by 5vi5t** [comment]
Ok, thank you
What pins are standart for software spi?

**Comment by awawa-dev** [comment]
On my Wemos d1 mini pins: D5 and D7

**Comment by 5vi5t** [comment]
D5 and D7 are hardware SPI pins, and don't work with DotStarMethod =(

**Comment by awawa-dev** [comment]
As I have no longer any SPI led strip I debug it today to make sure it still works.
On screenshot D5 & D7 captured by the analyzer, output starts when HyperHDR is starting sending data, otherwise it's flat zero:
![obraz](https://user-images.githubusercontent.com/69086569/107877973-e12c6200-6ecf-11eb-8833-1957ff76ee54.png)
If you have no output on these pins then probably there is some other cause.

**Comment by awawa-dev** [comment]
Software method allows to redefine default pins. I don't change them. On Esp8266 you can't redefine them anyway so always hardware pins are used.

**Comment by 5vi5t** [comment]
Ok, I understood
But dont work with SK9822 and WEMOS D1 mini.
I changed to DotStarSpiMethod and dont work too.
I tested with FastLED  sketch and all good

**Comment by awawa-dev** [comment]
Did you check if HyperSerialEsp8266 is receiving data at all (in stats)?

**Comment by 5vi5t** [comment]
I checked with a basic sketch adalight, the data is received, the highlight is working.

**Comment by awawa-dev** [comment]
There are some specific aspects for HyperSerialEsp8266 that can case not receiving the data and no output on led in result: different, rigorous  protocol not compatible with the sketch you provided and 2Mb that can be unsupported by hardware serial chip . So checking these statistics should be first step in the diagnostic because the sketch you used unfortunately tells us nothing about it.

**Comment by 5vi5t** [comment]
how can I do it?

**Comment by awawa-dev** [comment]
Please follow guide from other case: https://github.com/awawa-dev/HyperSerialEsp8266/issues/1

In short:
- configure HyperHDR properly for use AWA protocol & HyperSerialEsp8266 and try to run it for at least one minute.
- stop and close HyperHDR to release COM port
- using any serial port client listen to that COM and wait for statistics. They are sent every few seconds when HyperHDR is not sending led data to the device.
- if HyperHDR received at least one valid frame there will be a trace of that.

But first verify what serial chip is on your ESP8266 board.
